/*
 * Panel2.java
 *
 * Created on October 30, 2008, 4:38 PM
 */

package ppdm.gui.wizard.association;

import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import ppdm.algo.association.PartyID;
import ppdm.algo.association.Topology;
import ppdm.core.ErrorController;
import ppdm.gui.CustomTableColumnModel;

/**
 *
 * @author  Tran Huy Duc
 */
public class Panel2 extends javax.swing.JPanel {

    ArrayList<PartyID>  fullTopo;
    boolean             topoLoaded = false;
    
    /** Creates new form Panel2 */
    public Panel2() {
        initComponents();

        ImageIcon icon = new ImageIcon(ppdm.core.Config.LOGO_PATH);
        jlblIcon.setIcon(icon);
        jPanelStep.add(jlblIcon);

        init();
    }

    private void init() {
        jtblTopo.getSelectionModel().addListSelectionListener(new RowListener());
    }
    
    private class RowListener implements ListSelectionListener {
        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                onRowClick();
            }
        }
    }
    
    public void onRowClick() {
//        int rowIndex = jtblTopo.getSelectionModel().getLeadSelectionIndex();
        int rowIndex = jtblTopo.getSelectedRow();
//        Integer party = Integer.toString((Integer)jtblTopo.getValueAt(rowIndex, 0));
//        System.out.println(party);
        ArrayList<String> att = fullTopo.get(rowIndex).getAttribute();

        String[] colName = {"No.", "Attribute"};
        DefaultTableModel dtm = new DefaultTableModel(colName, 0);

        for (int i = 0; i < att.size(); i++) {
            Object[] rowData = {i + 1, att.get(i)};
            dtm.addRow(rowData);
        }
        jtblAttribute.setModel(dtm);
        CustomTableColumnModel.calcColumnWidths(jtblAttribute);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jscrpTopo = new javax.swing.JScrollPane();
        jtblTopo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblAttribute = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtnOpenTopo = new javax.swing.JButton();
        jtxtTopoFile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanelStep = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(775, 450));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(583, 332));

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 1));

        jscrpTopo.setAutoscrolls(true);

        jtblTopo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Party", "IP", "Port"
            }
        ));
        jtblTopo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jtblTopoComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jtblTopoComponentShown(evt);
            }
        });
        jscrpTopo.setViewportView(jtblTopo);

        jtblAttribute.setAutoCreateRowSorter(true);
        jtblAttribute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Attributes"
            }
        ));
        jScrollPane3.setViewportView(jtblAttribute);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Parties Configuration");

        jbtnOpenTopo.setText("Browse...");
        jbtnOpenTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpenTopoActionPerformed(evt);
            }
        });

        jLabel2.setText("Configuration Location:");

        jbtnView.setText("View");
        jbtnView.setEnabled(false);
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jscrpTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTopoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnOpenTopo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnView, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTopoFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnOpenTopo)
                    .addComponent(jbtnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                    .addComponent(jscrpTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextArea2.setRows(5);
        jTextArea2.setText("The coordinator reads the configuration, including the IP address and the attributes of each party,\nfrom the file.");
        jScrollPane1.setViewportView(jTextArea2);

        jLabel12.setText("Description:");

        jPanelStep.setBackground(new java.awt.Color(255, 255, 255));
        jPanelStep.setPreferredSize(new java.awt.Dimension(185, 450));

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Steps");

        jLabel6.setText("1. Project Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel7.setText("2*. Parties Configuration");

        jLabel8.setText("3. Data Configuration");

        jLabel9.setText("4. Connection Settings");

        jLabel10.setText("5*. Association Rule ");

        jlblIcon.setPreferredSize(new java.awt.Dimension(185, 140));

        jLabel3.setText(" and Party Type ");

        jLabel11.setText("Configuration");

        jSeparator4.setForeground(new java.awt.Color(51, 102, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 1));

        jLabel13.setText("*: For Coordinator Only");

        javax.swing.GroupLayout jPanelStepLayout = new javax.swing.GroupLayout(jPanelStep);
        jPanelStep.setLayout(jPanelStepLayout);
        jPanelStepLayout.setHorizontalGroup(
            jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStepLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStepLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(jLabel10))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
            .addComponent(jlblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanelStepLayout.setVerticalGroup(
            jPanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jlblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelStep, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelStep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(418, 418, 418))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jtblTopoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtblTopoComponentResized
// TODO add your handling code here:
}//GEN-LAST:event_jtblTopoComponentResized

private void jtblTopoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtblTopoComponentShown
// TODO add your handling code here:
}//GEN-LAST:event_jtblTopoComponentShown

private void jbtnOpenTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpenTopoActionPerformed
    jbtnOpenTopo.setEnabled(false);
    JFileChooser jfc = new JFileChooser();
    int jc = jfc.showDialog(null, "Open");
    if (jc == JFileChooser.APPROVE_OPTION) {
        try {
            File file = jfc.getSelectedFile();
            String filename = file.getAbsolutePath();
            jtxtTopoFile.setText(filename);
            fullTopo = Topology.readTopology(filename);

//            String[] colName = {"Party", "IP", "Port"};
//            DefaultTableModel dtm = new DefaultTableModel(colName, 0);
//
//            for (int i = 0; i < fullTopo.size(); i++) {
//                PartyID pid = fullTopo.get(i);
//                Object[] rowData = {i + 1, pid.IP, pid.port};
//                dtm.addRow(rowData);
//            }
//            jtblTopo.setModel(dtm);
//            CustomTableColumnModel.calcColumnWidths(jtblTopo);
            topoLoaded = true;
            jbtnView.setEnabled(topoLoaded);
        } catch (Exception ex) {

            topoLoaded = false;
            ErrorController.show(null, ex); 
        } finally {
            jbtnOpenTopo.setEnabled(true);
        }
    }
    jbtnOpenTopo.setEnabled(true);
}//GEN-LAST:event_jbtnOpenTopoActionPerformed

private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
    // TODO add your handling code here:
    try{
        String[] colName = {"Party", "IP", "Port"};
        DefaultTableModel dtm = new DefaultTableModel(colName, 0);

        for (int i = 0; i < fullTopo.size(); i++) {
            PartyID pid = fullTopo.get(i);
            Object[] rowData = {i + 1, pid.IP, pid.port};
            dtm.addRow(rowData);
        }
        jtblTopo.setModel(dtm);
        CustomTableColumnModel.calcColumnWidths(jtblTopo);
    } catch (Exception ex) {
        ErrorController.show(null, ex);
    }

}//GEN-LAST:event_jbtnViewActionPerformed

public void addTopoLoadedActionListener(ActionListener l) {
        jbtnOpenTopo.addActionListener(l);        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelStep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton jbtnOpenTopo;
    private javax.swing.JButton jbtnView;
    private javax.swing.JLabel jlblIcon;
    private javax.swing.JScrollPane jscrpTopo;
    private javax.swing.JTable jtblAttribute;
    private javax.swing.JTable jtblTopo;
    private javax.swing.JTextField jtxtTopoFile;
    // End of variables declaration//GEN-END:variables

}
