/*
 * MainFrame.java
 *
 * Created on September 8, 2008, 1:24 PM
 */

package ppdm.gui;

import java.awt.Toolkit;
import ppdm.core.topo.NewTopoFrame;
import java.beans.PropertyVetoException;
import ppdm.algo.association.AssociationParty;
import ppdm.algo.classification.Id3Party;
import ppdm.algo.clustering.KMeansParty;
import ppdm.core.Config;
import ppdm.core.ErrorController;
import ppdm.core.data.ConverterFrame;
import ppdm.core.data.DataViewer;
import ppdm.gui.wizard.association.AssoGUI;
import ppdm.gui.wizard.association.AssoResultFrame;
import ppdm.gui.wizard.classification.ClassificationGUI;
import ppdm.gui.wizard.classification.ClassificationResultFrame;
import ppdm.gui.wizard.clustering.KMeansGUI;
import ppdm.gui.wizard.clustering.KMeansResultFrame;

/**
 *
 * @author  Tran Huy Duc
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\Code\\Netbeans\\PPDM-Cache\\src\\ppdm\\images\\logoSmall.gif"));
        this.setLocationRelativeTo(null);
        new Config();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newAssoMenuItem = new javax.swing.JMenuItem();
        newClassMenuItem = new javax.swing.JMenuItem();
        newClusterMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecureMiner 1.0");

        desktop.setBackground(new java.awt.Color(204, 204, 204));

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        newAssoMenuItem.setText("New Association Rule Project");
        newAssoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAssoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newAssoMenuItem);

        newClassMenuItem.setText("New Classification Project");
        newClassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClassMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newClassMenuItem);

        newClusterMenuItem.setText("New Clustering Project");
        newClusterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClusterMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newClusterMenuItem);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        jMenu1.setText("Tools");

        jMenu2.setText("Data");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Viewer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Converter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);

        jMenu3.setText("Topology");

        jMenuItem3.setText("New");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Open");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_fileMenuActionPerformed

private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
// TODO add your handling code here:
    System.exit(1);
}//GEN-LAST:event_exitMenuItemActionPerformed


private void newAssoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                
    AssoGUI aprf = new AssoGUI();
    AssociationParty asso = aprf.getAssoParty();
    if (asso != null){
        AssoResultFrame apf = new AssoResultFrame(asso);
        apf.setTitle(asso.wrapper.projectName + " - Association Rule Mining Project");
        desktop.add(apf);
        apf.setVisible(true);
        try {
                apf.setSelected(true);                                               
        } catch (PropertyVetoException ex) {
            ErrorController.show(null, ex);
        }
    }
}

private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
    
}//GEN-LAST:event_aboutMenuItemActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    DataViewer sspf = new DataViewer();
    desktop.add(sspf);
    sspf.setVisible(true);
    try {
            sspf.setSelected(true);                                              
    } catch (PropertyVetoException ex) {
        ErrorController.show(null, ex);
    }
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    
}//GEN-LAST:event_jMenu2ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    ConverterFrame sspf = new ConverterFrame();
    desktop.add(sspf);
    sspf.setVisible(true);
    try {
            sspf.setSelected(true);                                              
    } catch (PropertyVetoException ex) {
        ErrorController.show(null, ex);
    }
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    NewTopoFrame sspf = new NewTopoFrame();
    desktop.add(sspf);
    sspf.setVisible(true);
    try {
            sspf.setSelected(true);                                              
    } catch (PropertyVetoException ex) {
        ErrorController.show(null, ex);
    }
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void newClusterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClusterMenuItemActionPerformed
    try {
        KMeansGUI kMeansGUI = new KMeansGUI();
        KMeansParty kMeansParty = kMeansGUI.getKMeansParty();
        if (kMeansParty != null) {
            KMeansResultFrame kmrf = new KMeansResultFrame(kMeansParty);
            desktop.add(kmrf);
            kmrf.setVisible(true);
            kmrf.setSelected(true);
        }
    } catch (Exception ex) {
        ErrorController.show(null, ex);
    }
    
}//GEN-LAST:event_newClusterMenuItemActionPerformed

private void newClassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClassMenuItemActionPerformed
    try {
        ClassificationGUI clGUI = new ClassificationGUI();
        Id3Party id3 = clGUI.getId3Party();    
        if (id3 != null){
            ClassificationResultFrame crf = new ClassificationResultFrame(id3);
            desktop.add(crf);
            crf.setVisible(true);        
            crf.setSelected(true);
        }
     } catch (Exception ex) {
            ErrorController.show(null, ex);
     }
}//GEN-LAST:event_newClassMenuItemActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        javax.swing.JFrame.setDefaultLookAndFeelDecorated(true);
//        javax.swing.JDialog.setDefaultLookAndFeelDecorated(true);
        try
        {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");            
        }
        catch (Exception ex)
        {
            System.out.println("Failed loading L&F: ");
            System.out.println(ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem newAssoMenuItem;
    private javax.swing.JMenuItem newClassMenuItem;
    private javax.swing.JMenuItem newClusterMenuItem;
    // End of variables declaration//GEN-END:variables

}
